#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

[ -d ITHACAoutput ] && rm -r ITHACAoutput
[ -d Lift ] && rm -r Lift
[ -e *.foam ] && rm -r *.foam
[ -e *.log ] && rm log.*
