#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

[ -d ITHACAOUTPUT ] && rm -r ITHACAOUTPUT
[ -e *.foam ] && rm -r *.foam
[ -e *.log ] && rm log.*
